### PR TITLE
welcome page

### PR DESCRIPTION
**Pull request by garlic0x1**
Add an extension package to print a nice welcome screen on startup.

ncurses screenshot:
image

sdl2 screenshot:
Screenshot from 2024-01-21 11-06-51

adding color should be possible but I am not sure how to use ANSI escape codes in a buffer.

### CODE REVIEW

**Comment by garlic0x1** [comment]
This feature can be disabled by adding `(setf lem-welcome:disable-welcome t)` to your config, and the message data is exported so it can be customized as well.  If opt-in is preferred over opt-out that can be done, some people might prefer it.

I also aligned the "Welcome to Lem!" line a bit better in this last commit.

**Comment by garlic0x1** [comment]
Changed `disable-welcome` to `enable-welcome` so it's off by default, just to be more conservative.

**Comment by cxxxr** [comment]
that's so cool :+1:

**Comment by vindarel** [comment]
@garlic0x1 Nice. Can you document it in https://github.com/lem-project/lem-project.github.io/ ?

**Pull request merged**
