### PR TITLE
Add trace commands to lisp-mode

### PR DESCRIPTION
**Pull request by cxxxr**
The following two commands have been added.
- `M-x lisp-trace-list (C-c T)`
- `M-x lisp-toggle-trace (C-c C-t)`

### CODE REVIEW

**Comment by vindarel** [comment]
Hello, when I use `C-c C-t` on a function, the feedback is NIL. It would help to know if the function just got traced or untraced.

C-c T when no function is traced only shows a blank box.

**Comment by cxxxr** [comment]
@vindarel
Thanks for the feedback!
I've changed the behavior.
If you have a better idea, please let me know.

**Comment by vindarel** [comment]
Thanks, it's clearer for me.

but: call C-c C-t, press "Enter" on the empty prompt without choosing anything -> "end of file on #<dynamic-extent STRING-INPUT-STREAM (unavailable) from "" : ]

**Comment by cxxxr** [comment]
Thanks!
This problem has been fixed.

**Pull request merged**
