### PR TITLE
[VI-MODE] • CLOS vi commands

### PR DESCRIPTION
**Pull request by theangelperalta**

### CODE REVIEW

**Comment by Sasanidas** [comment]
This seems really interesting, can you provide a statues of the pull request? (ping @theangelperalta )
Thanks!

**Comment by theangelperalta** [comment]
> This seems really interesting, can you provide a statues of the pull request? (ping @theangelperalta ) Thanks!

I've been away on holiday. I'll be picking up this work again.

**Comment by theangelperalta** [comment]
We will be revisiting this shortly. Sorry for the wait. This PR may need to be closed if rebase is too tough to manage.

**Comment by cxxxr** [comment]
Dont worry, I am always ready to welcome you.

**Comment by theangelperalta** [comment]
Closing this after evaluating the latest changes in `develop`  this PR is no longer necessary.

**Pull request closed without merging**
