### PR TITLE
open the source code of the sbcl as read-only

### PR DESCRIPTION
**Pull request by cxxxr**
Derrived from https://github.com/lem-project/lem/pull/1656

### CODE REVIEW

**Comment by sakurawald** [comment]
Looks good. The `source pattern` is retrived from the `micros` correctly, for both `repl:self` and `repl that starts as sbcl via roswell`.

image

**Comment by sakurawald** [comment]
By the way, can i ask what is the meaning of `WARNING: inconsistent form-number-translations`.
This occurs each time i find the definition on a built-in symbol.

**Comment by cxxxr** [comment]
> By the way, can i ask what is the meaning of WARNING: inconsistent form-number-translations ?

It seems to be handling an internal error in getting the position of the symbol definition and issuing a warning, but I do not know the details.
https://github.com/lem-project/micros/blob/25177e04a946365397a0848a6545399860d310d0/backend/sbcl.lisp#L892

**Comment by sakurawald** [comment]
> > By the way, can i ask what is the meaning of WARNING: inconsistent form-number-translations ?
> 
> It seems to be handling an internal error in getting the position of the symbol definition and issuing a warning, but I do not know the details. https://github.com/lem-project/micros/blob/25177e04a946365397a0848a6545399860d310d0/backend/sbcl.lisp#L892

Like the 

> > By the way, can i ask what is the meaning of WARNING: inconsistent form-number-translations ?
> 
> It seems to be handling an internal error in getting the position of the symbol definition and issuing a warning, but I do not know the details. https://github.com/lem-project/micros/blob/25177e04a946365397a0848a6545399860d310d0/backend/sbcl.lisp#L892

It's fine, do not affect the daily use. Only some built-in symbols like `defun` will trigger this warnning, most of them are fine.

**Comment by sakurawald** [comment]
> > By the way, can i ask what is the meaning of WARNING: inconsistent form-number-translations ?
> 
> It seems to be handling an internal error in getting the position of the symbol definition and issuing a warning, but I do not know the details. https://github.com/lem-project/micros/blob/25177e04a946365397a0848a6545399860d310d0/backend/sbcl.lisp#L892

It's fine, do not affect the daily use. Only some built-in symbols like defun will trigger this warnning, most of them are fine.

**Pull request merged**
