### PR TITLE
[VI-MODE] • Enhance define-vi-state to allow expose more of the defclass CLOS functionality.

### PR DESCRIPTION
**Pull request by theangelperalta**
The plan is to use inheritance to reduce code redundancy and improve the extensibility of vi-states, such as `visual` state. Currently, `visual` state has three sub states (`visual-char`, `visual-line`, `visual-block`), which produce code redundancy with state changes.

TODO: Follow-up with PR to refactor redundancy `visual` state.

### CODE REVIEW

**Comment by theangelperalta** [comment]
@cxxxr, this PR is ready for reviewing.

**Comment by cxxxr** [comment]
@theangelperalta 
It's very good.
There is a behavior change in normal-mode and insert-mode where the cursor color is the same in both modes, is this intended?

**Comment by theangelperalta** [comment]
> @theangelperalta It's very good. There is a behavior change in normal-mode and insert-mode where the cursor color is the same in both modes, is this intended?

Nice catch @cxxxr, it seems like I addressed the unintended behavioral change.

**Comment by cxxxr** [comment]
Thank you so much!
I think it is very good.

**Pull request merged**
