### PR TITLE
find files recursively

### PR DESCRIPTION
**Pull request by vindarel**
This makes using Lem more efficient :sunglasses: 

Selection_143

The new command should work for all platforms. 
We have a choice of programs to find files: 
  - [fd](https://github.com/sharkdp/fd), which is`fdfind` in Debian, excludes .git, node_modules and the like by default
  - find
  - a lisp way

This is NOT like "find file in project", which could be done later on. This is only "find a file with a choice of all files in subdirectories, starting from this buffer's directory".

I settled on CLOS `eql` specializers to dispatch by the chosen finder program, so the user has built-in configuration options (around methods, etc).

subject to review:

- I introduced my STR library as a dependency. It is lightweight and, albeit not strictly necessary for this PR, I believe it is very handy (and popular!).
- on `#+unix` (I believe it includes Mac OS?) I call `which` to check that a program is present in the system. On non-unix, we fallback to the lispy method.
- a couple comments inline.

### CODE REVIEW

**Review by cxxxr — COMMENTED** [review]
Ooh, this is very useful!
It seems like a good idea to make it the default function of `find-file`.

I made some comments, thank you in advance.

**Comment by Sasanidas** [comment]
> Ooh, this is very useful! It seems like a good idea to make it the default function of `find-file`.
> 
> I made some comments, thank you in advance.

Umm, maybe an overkill to make the default find-file version?

**Comment by vindarel** [comment]
>  It seems like a good idea to make it the default function of find-file.

It might be a nice(r) default, but not in this current state:

- I am not using `prompt-file` but prompt for string, so we don't have the current directory on the prompt, so we can't go up one directory :s 
  - (any ideas?)
- you can't run this on the HOME or on a directory with too many files :s 
  - need to find workarounds, or be able to kill the underlying process, etc.

For the default, we might compare what popular editors do? Personally, I think such a feature is super handy (according it doesn't come with obvious issues, like now).

**Comment by cxxxr** [comment]
Hmmm, I see.
Maybe it's similar to Command+P (Control+P) in VSCode.

**Comment by cxxxr** [comment]
@vindarel Can I merge this PR already?

**Comment by vindarel** [comment]
wait wait! I will improve it with your reviews.

**Comment by vindarel** [comment]
```lisp
(define-command find-file-recursively (arg) ("p")
  ;; what is arg for?
```

Shall I use the arg, and how? I'm investigating this.

**Comment by cxxxr** [comment]
Oh, sorry, I'm not in a hurry.
Thank you.

**Comment by cxxxr** [comment]
> Shall I use the arg, and how? I'm investigating this.

Maybe we can add it when we need it.

**Comment by vindarel** [comment]
It's better (maybe good?) now!

- code review
- if the process of finding finds recursively takes too long (5s by default), kill the thread and the process, fallback to find-file
- fixed the lispy way to find files 

It works for me©

**Comment by cxxxr** [comment]
It is very cool!
Thank you so much 👍

**Pull request merged**
