### PR TITLE
feature: add `maximize-frame` and `minimize-frame` command for lem sdl2 version.

### PR DESCRIPTION
**Pull request by sakurawald**
The issue: https://github.com/lem-project/lem/issues/1583

### CODE REVIEW

**Comment by sakurawald** [comment]
To start up lem editor and maximize it, append this to `init.lisp`:
```
(lem-sdl2/frame:maximize-frame)
```

**Comment by cxxxr** [comment]
That's good.
If I had to say something, I'd like to put it in the same package as toggle-frame-fullscreen and unify the interface.
I also want to make it compatible with other than SDL2.

https://github.com/lem-project/lem/pull/831/files
Wouldn't it be nice to define the interface like the PR of the link destination?

**Comment by sakurawald** [comment]
> I tried it on a macos, but it seems that the process will end abnormally if you don't use sdl2:in-main-thread.
> 
> I was able to get it working on macOS by doing the following
> 
> ```commonlisp
> (sdl2:in-main-thread ()
>     (sdl2:maximize-window (lem-sdl2/display::display-window (lem-sdl2/display:current-display))))
> ```

Hah, sorry, i forget about this. 
It works well in `linux`, i am not very sure about it in other platforms.

I have modified the source, and you can help me modify it if anything is wrong.

**Comment by cxxxr** [comment]
Thank you.
Can I merge it and then make changes?
I'll move the command definitions to lem-core/commands/frame.

**Comment by sakurawald** [comment]
> Thank you. Can I merge it and then make changes? I'll move the command definitions to lem-core/commands/frame.

Sure!

**Comment by sakurawald** [comment]
One more question: I create the `frame.lisp` file in `frontends/sdl2/frame.lisp`, it's because the usage of `sdl2` package.
I didn't define the commands in `src`, because i don't know if it's not sdl2 version.

**Pull request merged**
