### PR TITLE
Add thingatp functionality

### PR DESCRIPTION
**Pull request by Sasanidas**
A very Emacsy approach to get the "thing at point", the idea is to extend it with more types :+1:

### CODE REVIEW

**Review by cxxxr — COMMENTED** [review]
I think it is a very nice feature!
I've made few comments :pray:

**Comment by Sasanidas** [comment]
Oh my, so many small mistakes, I guess that's happens when I copy and paste :facepalm:

**Comment by Sasanidas** [comment]
I think I solve most of them :raised_hands:

**Comment by cxxxr** [comment]
Thank you so much!

**Pull request merged**
