### PR TITLE
Fix commands with % movement

### PR DESCRIPTION
**Pull request by davidsun0**
- Fix issue where commands like y% were interpreted as y1% (#1402)
- Add regression tests

### CODE REVIEW

**Comment by cxxxr** [comment]
Thank you.
By the way, the vi-mode test is failing, but is this related to your changes?

**Comment by davidsun0** [comment]
The failing test is for vi macros, but the test doesn't use %, so I don't think it's caused by my changes. I'll try debugging it and see what I find.

**Comment by cxxxr** [comment]
I'm sorry to have merged without waiting for CI, but it seems that I've started to fail with this PR.
https://github.com/lem-project/lem/pull/1395

**Comment by davidsun0** [comment]
@cxxxr Thanks for waiting. I fixed my mistake and improved the `dd` test case.

**Comment by cxxxr** [comment]
Thank you!

**Pull request merged**
