### PR TITLE
Adds ZQ to vi mode

### PR DESCRIPTION
**Pull request by anotherlusitano**
Adds [ZQ](https://vimdoc.sourceforge.net/htmldoc/editing.html#ZQ) to vi mode.
This solve the #1189

### CODE REVIEW

**Comment by mychris** [comment]
I think you mean ZQ, not ZG.
https://vimdoc.sourceforge.net/htmldoc/editing.html#ZQ

**Comment by anotherlusitano** [comment]
Sorry my bad, I'll change it.

**Comment by anotherlusitano** [comment]
Done!

**Comment by cxxxr** [comment]
Thank you!

**Pull request merged**
